main/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views

app_name = "main"

urlpatterns = [
    path("",views.homepage, name="homepage"),
    path("register/", views.register,name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("change_password/", views.change_password, name="change_password")
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="main/password_reset.html"), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="main/password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="main/password_reset_sent.html"), name='password_reset_done'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="main/password_reset_done.html"), name='password_reset_complete'),
    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User




        

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=20, required=True)
    last_name = forms.CharField(max_length=20, required=True)    
    class Meta:
        model = User
        fields = ("username", "email","first_name","last_name","password1", "password2")


    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields =  (
            'username',
            'email',
            'first_name',
            'last_name',
        )
        labels = {
            'username': _('Nama Pengguna'),
            'email': _('Email'),
            'first_name': _('Nama Depan'),
            'last_name': _('Nama Belakang')
        }
        help_texts = {
            'username': _('Diperlukan. 150 karakter atau kurang. Hanya huruf, angka, dan @/./+/-/_ saja.'),
        }


              

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import (
    AuthenticationForm, 
    PasswordChangeForm,
    UserChangeForm
)
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from django.contrib import messages
from .forms import NewUserForm, EditProfileForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.http import HttpResponse


# Create your views here.
def homepage(request):
    return render(request = request,
                  template_name='main/home.html',
                  context = {})

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Akun baru dibuat: {username}")
            login(request, user)
            messages.info(request,f"Anda masuk sebagai: {username}")
            return redirect("main:homepage")

        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            return render(request = request,
                          template_name = "main/register.html",
                          context={"form":form})

    form = NewUserForm
    return render(request = request,
                  template_name = "main/register.html",
                  context={"form":form})

def logout_request(request):
    logout(request)
    # messages.info(request, "Berhasil Keluar Akun!")
    return redirect("main:login")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request,f"Anda masuk sebagai: {username}")
                return redirect("main:homepage")
            else:
                messages.error(request, "Username atau Kata Sandi Tidak Sesuai")
        else:
            messages.error(request, "Username atau Kata Sandi Tidak Sesuai")
    form = AuthenticationForm()
    return render(request, 
                    "main/login.html", 
                    {"form":form})

def profile(request):
    args = {"user": request.user}
    return render(request, "main/profile.html", args)

def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect("main:profile")
    else:
        form = EditProfileForm(instance=request.user)
        args = {"form": form}
        return render(request,"main/edit_profile.html",args)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("main:profile")
        else:
            return redirect("main:change_password")
    else:
        form = PasswordChangeForm(user=request.user)
        args = {"form": form}
        return render(request,"main/change_password.html",args)

main/templates/main/base.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-PSU Kabupaten Sidoarjo</title>
  
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  
    <!-- CSS -->
    {% block css %}
    <!-- Add your css here -->
    {% endblock css %}
  </head>
  <body>
    <nav class="navbar navbar-light" style="background-color: #03a678;">
      <a class="navbar-brand" href="/">
          <img src="http://4.bp.blogspot.com/-FtOrR7FqtEg/Tdufk5MUD9I/AAAAAAAADrE/1FMbaYHMrR8/s320/Kabupaten_Sidoarjo.png" class="m-2" alt="logo_sidoarjo" width="75" height="75">
      </a>
      <span class="text-white" style="font-size: x-large;">E-PSU PERUMAHAN KABUPATEN SIDOARJO</span> 
    </nav>
  
    {% include "main/includes/navbar.html" %}
    <div class="container">
      <br>
      {% block content %}
      {% endblock %}
    </div> 
    
    {% include "main/includes/footer.html" %}
    
    
    <!-- JS -->
    {% block js %}
    <!-- Add your js here -->
    {% endblock js %}
  </body>

main/templates/main/change_password.html
{% extends "main/base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<h1 style="text-align:center">Ubah Kata Sandi</h1><br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div id="div_id_old_password" class="form-group"> <label for="id_old_password" class=" requiredField">
                Kata Sandi Lama<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="old_password" autocomplete="current-password" autofocus class="textinput textInput form-control" required id="id_old_password"> </div> </div> <div id="div_id_new_password1" class="form-group"> <label for="id_new_password1" class=" requiredField">
                Kata Sandi Baru<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="new_password1" autocomplete="new-password" class="textinput textInput form-control" required id="id_new_password1"> <small id="hint_id_new_password1" class="form-text text-muted"><ul><li>Kata sandi anda tidak boleh mirip dengan informasi pribadi anda.</li><li>Kata sandi anda harus memiliki minimal 8 karakter.</li><li>Jangan menggunakan kata sandi yang sering digunakan.</li><li>Kata sandi anda tidak boleh hanya angka saja.</li></ul></small> </div> </div> <div id="div_id_new_password2" class="form-group"> <label for="id_new_password2" class=" requiredField">
                Konfirmasi Kata Sandi Baru<span class="asteriskField"></span> </label> <div class=""> <input type="password" name="new_password2" autocomplete="new-password" class="textinput textInput form-control" required id="id_new_password2"> </div> </div>
        <a href="/edit_profile"><strong>Ubah Profil</strong></a><br><br>
        <button type="submit" class="btn btn-primary"><strong>Ubah</strong></button> <br><br>
    </form>
</div>
{% endblock %}

main/templates/main/edit_profile.html
{% extends "main/base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<h1 style="text-align:center">Ubah Profil</h1><br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}   
        <a href="/change_password"><strong>Ubah Kata Sandi</strong></a><br><br>
        <button type="submit" class="btn btn-primary"><strong>Ubah</strong></button>
    </form>
</div>
{% endblock %}

main/templates/main/header.html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>E-PSU Kabupaten Sidoarjo</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!-- CSS -->
  {% block css %}
  <!-- Add your css here -->
  {% endblock css %}
</head>
<body>
  <nav class="navbar navbar-light" style="background-color: #03a678;">
    <a class="navbar-brand" href="/">
        <img src="http://4.bp.blogspot.com/-FtOrR7FqtEg/Tdufk5MUD9I/AAAAAAAADrE/1FMbaYHMrR8/s320/Kabupaten_Sidoarjo.png" class="m-2" alt="logo_sidoarjo" width="75" height="75">
    </a>
    <span class="text-white" style="font-size: x-large;">E-PSU PERUMAHAN KABUPATEN SIDOARJO</span> 
  </nav>

  {% include "main/includes/navbar.html" %}
  <div class="container">
    <br>
    {% block content %}
    {% endblock %}
  </div> 
  
 
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <!-- JS -->
  {% block js %}
  <!-- Add your js here -->
  {% endblock js %}
</body>

main/templates/main/home.html
{% extends "main/base.html" %}

{% block content %}
    
{% endblock %} 

main/templates/main/includes/footer.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<footer class="page-footer font-small pt-4" style="background-color: #03a678;">
    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-3">
                <!-- Footer Content -->
                <h5 class="text-uppercase text-white">Footer Content</h5>
                <p class="text-white">Here you can use rows and columns to organize your footer content.</p>
            </div>

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-2 mb-md-0 mb-3">
                <!-- Links -->
                <h5 class="text-uppercase text-white">Pelaporan</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!" class="text-white">Link 1</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 2</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 3</a>
                    </li>
                </ul>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-md-0 mb-3">
                <!-- Links -->
                <h5 class="text-uppercase text-white">Pemantauan</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!" class="text-white">Link 1</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 2</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 3</a>
                    </li>
                </ul>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 mb-md-0 mb-3">
                <!-- Links -->
                <h5 class="text-uppercase text-white">Pengelolaan</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!" class="text-white">Link 1</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 2</a>
                    </li>
                    <li>
                        <a href="#!" class="text-white">Link 3</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-white" style="background-color: #025b42">
        © 2020 Copyright:<a href="https://mdbootstrap.com/" class="text-white"> Kabupaten Sidoarjo</a>
    </div>

    </footer>
   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

main/templates/main/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #025b42;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <a class="nav-link text-white" href="/">Beranda <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pelaporan
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Ajukan Laporan</a>
                  <a class="dropdown-item" href="#">Cek Status</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
              </div>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pemantauan
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
              </div>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pengelolaan
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Sosialisasi Serah Terima</a>
                  <a class="dropdown-item" href="#">Laporan Masyarakat</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
              </div>
          </li>
      </ul>
      <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            
            <li class="nav-item dropdown">
              <a id="navbarDropdown" class="nav-link text-white dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                  {{user.username}} <span class="caret"></span>
              </a>
            

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/profile">Profil</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/logout">Logout</a>

                  <form id="logout-form" action="#" method="POST" style="display: none;">
                      <!-- Insert csrf token here -->
                  </form>
              </div>
            </li>
            
          {% else %} 
          <li class="nav-item">
              <a class="nav-link text-white" href="/login">Login</a>
          </li>

          <li class="nav-item">
              <a class="nav-link text-white" href="/register">Register</a>
          </li>
          {% endif %}
      </ul>
  </div>
</nav>

main/templates/main/password_reset.html
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<style>
  body {
  background-color: #ced0cf;
  min-height: 100vh; }

.brand-wrapper {
  margin-bottom: 19px; }
  .brand-wrapper .logo {
    height: 37px; }


.login-card {
  border: 0;
  border-radius: 27.5px;
  box-shadow: 0 10px 30px 0 rgba(172, 168, 168, 0.43);
  overflow: hidden;
  }
  .login-card-img {
    border-radius: 0;
    position: absolute;
    width: 100%;
    height:80%;
    -o-object-fit: contain;
    object-fit: contain;
     } 
  .login-card .card-body {
    padding: 85px 60px 60px; }
    @media (max-width: 422px) {
      .login-card .card-body {
        padding: 35px 24px; } }
  .login-card-description {
    font-size: 25px;
    color: #000;
    font-weight: normal;
    margin-bottom: 23px; }
  .login-card form {
    max-width: 326px; }
  .login-card .form-control {
    border: 1px solid #d5dae2;
    margin-bottom: 20px;
    min-height: 45px;
    font-size: 13px;
    line-height: 15;
    font-weight: normal; }
    .login-card .form-control::-webkit-input-placeholder {
      color: #919aa3; }
    .login-card .form-control::-moz-placeholder {
      color: #919aa3; }
    .login-card .form-control:-ms-input-placeholder {
      color: #919aa3; }
    .login-card .form-control::-ms-input-placeholder {
      color: #919aa3; }
    .login-card .form-control::placeholder {
      color: #919aa3; }
  .login-card .login-btn {
    padding: 13px 20px 12px;
    background-color: #000;
    border-radius: 4px;
    font-size: 17px;
    font-weight: bold;
    line-height: 20px;
    color: #fff;
    margin-bottom: 24px; }
    .login-card .login-btn:hover {
      border: 1px solid #000;
      background-color: transparent;
      color: #000; }
  .login-card .forgot-password-link {
    font-size: 14px;
    color: #919aa3;
    margin-bottom: 12px; }
  .login-card-footer-text {
    font-size: 16px;
    color: #0d2366;
    margin-bottom: 60px; }
    @media (max-width: 767px) {
      .login-card-footer-text {
        margin-bottom: 24px; } }
  .login-card-footer-nav a {
    font-size: 14px;
    color: #919aa3; }


</style>
{% load crispy_forms_tags %}
{% block content %}
<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
        <div class="card login-card" style="background-color: #025b42;">
            <div class="row no-gutters">
                <div class="col-md-6 d-flex justify-content-center align-items-center">
                    <a href="/" >
                        <img src="http://4.bp.blogspot.com/-FtOrR7FqtEg/Tdufk5MUD9I/AAAAAAAADrE/1FMbaYHMrR8/s320/Kabupaten_Sidoarjo.png" alt="logo_sidoarjo"  height="350" width="375">
                    </a>
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h4><strong class="text-white">ATUR ULANG KATA SANDI</strong></h4> 
                        <br> 
                        <form method="POST" class="text-white">
                            {% csrf_token %}
                            <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
                              Email<span class="asteriskField"></span> </label> <div class=""> <input type="email" name="email" autocomplete="email" maxlength="254" class="emailinput form-control" required id="id_email"> </div> </div>
                            <button  type="submit" class="btn btn-primary"><strong>Atur Ulang</strong></button>
                        </form>
                        <span class="text-white">Jika belum memiliki akun, silahkan <a href="/register"><strong>Daftar</strong></a> terlebih dahulu.</span>
                        <br>
                        <a href="/login"><strong>Masuk</strong></a>
                        <br>
                        <br>
                    </div> 
                </div>    
            </div>
            
        </div>   
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}

main/templates/main/register.html
{% load static %}
<link rel="stylesheet" href="{% static 'main/css/register.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% load crispy_forms_tags %}
<body class="form-v6">
	<div class="page-content">
		<div class="form-v6-content">
			<form class="form-detail text-white" method="post">
        <h2>REGISTRASI</h2>
        <a href="/" class="d-flex justify-content-center align-items-center" >
          <img src="http://4.bp.blogspot.com/-FtOrR7FqtEg/Tdufk5MUD9I/AAAAAAAADrE/1FMbaYHMrR8/s320/Kabupaten_Sidoarjo.png" alt="logo_sidoarjo"  height="200" width="225">
		</a><br>
		{% csrf_token %}
				<div id="div_id_username" class="form-group form-group-align"> <label for="id_username" class=" requiredField">
          Nama Pengguna </label> <div class=""> <input type="text" name="username" maxlength="150" autofocus class="textinput textInput form-control" required id="id_username"> <small id="hint_id_username" class="form-text text-white">Diperlukan. 150 karakter atau kurang. Hanya huruf, angka, dan @/./+/-/_ saja</small> </div> </div> 
        <div id="div_id_email" class="form-group form-group-align"> <label for="id_email" class=" requiredField">
          Email </label> <div class=""> <input type="email" name="email" class="emailinput form-control" required id="id_email"> </div> </div> 
        <div id="div_id_first_name" class="form-group form-group-align"> <label for="id_first_name" class=" requiredField">
          Nama Depan </label> <div class=""> <input type="text" name="first_name" maxlength="20" class="textinput textInput form-control" required id="id_first_name"> </div> </div> 
        <div id="div_id_last_name" class="form-group form-group-align"> <label for="id_last_name" class=" requiredField">
          Nama Belakang</label> <div class=""> <input type="text" name="last_name" maxlength="20" class="textinput textInput form-control" required id="id_last_name"> </div> </div> 
        
        <div id="div_id_password1" class="form-group form-group-align"> <label for="id_password1" class=" requiredField">
          Kata Sandi </label> <div class=""> <input type="password" name="password1" autocomplete="new-password" class="textinput textInput form-control" required id="id_password1"> <small id="hint_id_password1" class="form-text text-white"><ul><li>Kata sandi anda tidak boleh mirip dengan informasi pribadi anda.</li><li>Kata sandi anda harus memiliki minimal 8 karakter.</li><li>Jangan menggunakan kata sandi yang sering digunakan.</li><li>Kata sandi anda tidak boleh hanya angka saja.</li></ul></small> </div> </div> 
        <div id="div_id_password2" class="form-group form-group-align"> <label for="id_password2" class=" requiredField">
          Konfirmasi Kata Sandi</label> <div class=""> <input type="password" name="password2" autocomplete="new-password" class="textinput textInput form-control" required id="id_password2"> <small id="hint_id_password2" class="form-text text-white">Masukkan kata sandi anda yang sudah anda masukkan sebelumnya.</small> </div> </div> 
        <br><div style="position:absolute;left: 45%;"><button  type="submit" class="btn btn-primary"><strong>Daftar</strong></button></div>
		<br><br><br>
        <span class="text-white" style="margin-left:70">Jika sudah memiliki akun, silahkan <a href="/login"><strong>Masuk</strong></a> menggunakan akun anda.</span> <br>
			</form>
		</div>
	</div>
</body>